### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by philn** [gdesmott/gst-log-parser#1]
Hi @gdesmott !
Thanks for providing this nice crate. I wrote a tool using it as dependency: https://github.com/philn/gst-log-diff
Can you please publish the parser on crates.io? If possible I would like to not depend on the git version :)

**Comment by gdesmott** [comment]
Sure, I never bothered releasing it as I was assuming I'd be the only user. :D 
But yeah, I'll do somple cleanup (#2) and then will do a proper release.

**Comment by gdesmott** [comment]
Here we go! https://crates.io/crates/gst-log-parser
