### ISSUE TITLE
Move examples to a sub-crate?

### ISSUE THREAD

**Issue by philn** [gdesmott/gst-log-parser#2]
Doing so would probably simplify the dependencies tree of the lib.

**Comment by gdesmott** [comment]
Yes sounds like a good idea. This was literally my first Rust project (I started it as a learning tool) so there is definitely room to make things cleaner.
Any suggestion welcome!

**Comment by philn** [comment]
I can send a PR if you want :)

**Comment by gdesmott** [comment]
Oh that would be great. So you'd turn the root `Cargo.toml` to a workspace and have the parser and the tools live in their own crate in subdirectories?

**Comment by philn** [comment]
Yes :)

**Comment by gdesmott** [comment]
Perfect; PR welcome :)
