### ISSUE TITLE
Latency filtering

### ISSUE THREAD

**Issue by boxerab** [gdesmott/gst-log-parser#8]
Very nice little tool !

I am using this to filter latency trace in attached file. 

`cargo run --release --example check-latency lat.txt filter-higher 0`

I only see a single element in the output, `udpsrc`, should I not see all elements ? Is filtering by nanaosecond ?

Thanks!

[lat.zip](https://github.com/gdesmott/gst-log-parser/files/4476835/lat.zip)

**Comment by gdesmott** [comment]
The tool was filtering only, the total pipeline latency, not the per-element one. Fixing that.

The filtering is in ms, you can use this command to check the doc:
```
$ cargo run --release --example check-latency -- filter-higher --help
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/examples/check-latency filter-higher --help`
check-latency-filter-higher 0.1.2
Guillaume Desmottes <guillaume@desmottes.be>
Check for latency higher than a value

USAGE:
    check-latency <input> filter-higher <min>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <min>    The minimum latency to display, in ms
```

**Comment by boxerab** [comment]
Thanks for the quick fix.
